import { useState } from 'react'

interface EvalViewerTabProps {
  type: 'skill' | 'agent'
  name: string
}

export function EvalViewerTab({ type, name }: EvalViewerTabProps) {
  const [htmlPath, setHtmlPath] = useState<string | null>(null)

  // The eval viewer HTML will be generated by skill-creator/agent-create via CLI
  // and its path will be available in the workspace directory
  // For now, allow manual path input

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {!htmlPath ? (
        <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
            Eval Viewer HTML 경로를 입력하거나, Tests 탭에서 테스트를 실행하면 자동으로 로드됩니다.
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <input
              placeholder="eval viewer HTML 파일 경로"
              onChange={(e) => {
                if (e.target.value) setHtmlPath(e.target.value)
              }}
              style={{
                flex: 1, padding: '5px 10px', fontSize: 12,
                background: 'var(--bg-main)', border: '1px solid var(--border)',
                borderRadius: 'var(--radius-sm)', color: 'var(--text-primary)',
                outline: 'none',
              }}
            />
          </div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>
            예: ~/.claude/skills/{name}-workspace/iteration-1/review.html
          </div>
        </div>
      ) : (
        <iframe
          src={`file://${htmlPath}`}
          sandbox="allow-scripts allow-same-origin"
          style={{
            flex: 1, border: 'none', background: '#fff',
            borderRadius: 'var(--radius-sm)',
          }}
          title="Eval Viewer"
        />
      )}
    </div>
  )
}
